# Generated by Django 4.1 on 2022-08-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("nivel", models.IntegerField()),
                ("password", models.CharField(max_length=16)),
                ("fotodeperfil", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=10)),
                ("descripcion", models.TextField()),
                ("valoracion", models.IntegerField()),
                ("fecha", models.DateField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("valoracion", models.IntegerField()),
                ("fecha", models.DateField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.post"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.usuario"
                    ),
                ),
            ],
        ),
    ]
